### PR TITLE
Defined Base.copy as per-required, e.g., by NLSolve.jl OneDifferentiable

### PR DESCRIPTION
**Pull request by amartinhuertas**

### CODE REVIEW

**Comment by fverdugo** [comment]
Thanks for this @amartinhuertas !

**Comment by fverdugo** [comment]
Feel free to register a new patch version.

**Comment by fverdugo** [comment]
Hi @amartinhuertas!

this PR is making Gridap to crash. See e.g., https://github.com/gridap/Gridap.jl/pull/669/checks?check_run_id=3811313579#step:6:229

**in any case this PR is correct!**

The problem is that now we end up working with SparseMatricesSCR (as it should be) and it seems
that `lu!` is not yet implemented for this type.

We have 2 options.

1. Implement it now and see if Gridap works again
2. Pin SparseMatricesCSR to the previous version in Gridap and implement the missing method later.

Can you help with either 1. or 2. ?

**Comment by amartinhuertas** [comment]
Yes. I would pursue 1. better. How `lu!` should be implemented for this type? By transforming to CSC? (just guessing ... I did not give it a profound though).

**Comment by amartinhuertas** [comment]
> See e.g., https://github.com/gridap/Gridap.jl/pull/669/checks?check_run_id=3811313579#step:6:229

Is there only one test that fails or there are others as well? I am wondering if we need something else than `lu` ...

**Comment by amartinhuertas** [comment]
> It should be a method convert for this somewhere.

Yes, indeed, there is. 

> Of course, when we have a 0-based csr the most efficient way would be to provide the raw data to UMFPACK but I don't know if we have time to do this now...

Agreed. Let us leave this for another moment. I will open an issue.

**Comment by fverdugo** [comment]
When we have a 1-based csr, perhaps we can build a csc with the raw data (which will be the transpose) and then call lu! with Tanspose(csc). Perhaps there is an efficient implementation of  lu! for `Transpose{<:SparseMatrix}`. In any case, this is just an optimization that can be done later.

**Comment by amartinhuertas** [comment]
> I don't know. grep -r SparseMatrixSCR test/ will give you the potentially problematic tests.

Ok. I will run the tests locally.

**Pull request merged**
